branch-defaults:
  master:
    environment: Default-Environment
environment-defaults:
  Default-Environment:
    branch: null
    repository: null
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: kazuya
  default_region: ap-northeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
